version: "3.9"
services:
  python:
    build: .
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: password