version: "3.9"
services:
  pytest:
    build: .
    environment:
      TZ: 'Asia/Shanghai'
    depends_on:
      - mysql
      - postgres
  mysql:
    image: mysql:8
    command: 'mysqld --default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - '3306:3306'
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'mysql_user'
      MYSQL_PASSWORD: 'mysql_password'
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: 'Asia/Shanghai'
      POSTGRES_USER: 'postgres_user'
      POSTGRES_PASSWORD: 'postgres_password'
      POSTGRES_DB: 'postgres_db'
